# Generated by Django 4.0.4 on 2022-04-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
