# Generated by Django 4.0.4 on 2022-04-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0003_workexperiencedetail_technicalskill_otherskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiencedetail',
            name='company',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
