# Generated by Django 4.0.4 on 2022-04-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0004_workexperiencedetail_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetail',
            name='program',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
