# Generated by Django 4.0.4 on 2022-04-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0006_rename_resume_educationdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='degree',
            field=models.CharField(choices=[('PhD', 'PhD'), ("Master's Degree", "Master's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ('High School Diploma', 'High School Diploma'), ('Middle School Diploma', 'Middle School Diploma'), ('Elementary School Diploma', 'Elementary School Diploma'), ('Professional Qualification', 'Professional Qualification')], max_length=26),
        ),
    ]
