# Generated by Django 4.0.4 on 2022-04-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0007_alter_educationdetail_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='cv_file',
        ),
    ]
