# Generated by Django 4.0.4 on 2022-04-20 16:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0008_remove_applicantprofile_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
