# Generated by Django 4.0.4 on 2022-04-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0009_alter_applicantprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperiencedetail',
            old_name='resume',
            new_name='user',
        ),
    ]
