# Generated by Django 4.0.4 on 2022-04-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0010_rename_resume_workexperiencedetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='looking_for_work',
        ),
    ]
