# Generated by Django 4.0.4 on 2022-04-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants_app', '0012_alter_otherskill_name_alter_technicalskill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantprofile',
            options={'verbose_name_plural': 'Applicant Profiles'},
        ),
    ]
