# Generated by Django 4.0.4 on 2022-04-28 10:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants_app', '0013_alter_applicantprofile_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otherskill',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalskill',
            unique_together={('name', 'user')},
        ),
    ]
