# Generated by Django 4.0.4 on 2022-04-21 07:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0002_alter_companyprofile_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
