# Generated by Django 4.0.4 on 2022-04-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0005_rename_profile_picture_companyprofile_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name_plural': 'Company Profiles'},
        ),
    ]
