# Generated by Django 4.0.4 on 2022-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0003_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Intermediate', 'Intermediate'), ('Senior or Executive', 'Senior or Executive')], max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule',
            field=models.CharField(choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Flexible', 'Flexible'), ('Shift Work', 'Shift Work')], default='Full-Time', max_length=10),
            preserve_default=False,
        ),
    ]
