# Generated by Django 4.0.4 on 2022-04-22 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0007_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
