# Generated by Django 4.0.4 on 2022-04-23 06:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0008_jobapplication_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='additional_documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
    ]
