# Generated by Django 4.0.4 on 2022-04-23 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_app', '0009_alter_jobapplication_additional_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
