# Generated by Django 4.0.4 on 2022-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0011_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
